version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DOCKER_DB_NAME}
      POSTGRES_USER: ${DOCKER_DB_USER}
      POSTGRES_PASSWORD: ${DOCKER_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_NAME: ${DOCKER_DB_NAME}
      DB_USER: ${DOCKER_DB_USER}
      DB_PASSWORD: ${DOCKER_DB_PASSWORD}
      DB_HOST: ${DOCKER_DB_HOST}
      DB_PORT: ${DOCKER_DB_PORT}
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data:
